In [ ]:
# import numpy as np

# # 定义逻辑斯蒂克（logistics）目标函数
# def logistics_function(X, y, weights):
#     z = np.dot(X, weights)
#     predictions = 1 / (1 + np.exp(-z))
#     loss = -np.mean(y * np.log(predictions) + (1 - y) * np.log(1 - predictions))
#     return loss

# # 计算逻辑斯蒂克（logistics）目标函数关于参数的梯度
# def gradient(X, y, weights):
#     z = np.dot(X, weights)
#     predictions = 1 / (1 + np.exp(-z))
#     error = predictions - y
#     grad = np.dot(X.T, error) / len(X)  #logit损失函数对模型形式参数的偏导
#     return grad

# # 小批量梯度下降算法
# def mini_batch_gradient_descent(X, y, learning_rate=0.01, lamda =0.01,batch_size=32, num_epochs=100):
#     # 初始化参数
#     weights = np.random.randn(X.shape[1])
    
#     # 迭代训练
#     for epoch in range(num_epochs):
#         # 在每个epoch开始时，对训练数据进行洗牌
#         shuffled_indices = np.random.permutation(len(X))
#         X_shuffled = X[shuffled_indices]
#         y_shuffled = y[shuffled_indices]
        
#         # 按批次更新参数
#         for batch_start in range(0, len(X), batch_size):
#             # 获取当前批次的数据
#             X_batch = X_shuffled[batch_start:batch_start+batch_size]
#             y_batch = y_shuffled[batch_start:batch_start+batch_size]
            
#             # 计算梯度
#             grad = gradient(X_batch, y_batch, weights)
            
#             # 更新参数
#             batch_weights = weights - learning_rate * grad
#             weights = weights - learning_rate * grad +lamda*
            
#         # 计算当前参数下的目标函数值
#         cost = logistics_function(X, y, weights)
        
#         # 输出损失
#         print("Epoch: {}, Cost: {}".format(epoch, cost))

# # # 创建训练数据（示例数据，自行替换）
# # np.random.seed(0)
# # X = np.random.randn(1000, 3)
# # y = np.random.randint(2, size=1000)

# # # 添加偏置项
# # X_bias = np.hstack((np.ones((X.shape[0], 1)), X))

# # 运行小批量梯度下降算法
# mini_batch_gradient_descent(X_bias, y, learning_rate=0.01, batch_size=32, num_epochs=100)


In [30]:
import numpy as np

# 定义逻辑斯蒂克（logistics）目标函数
def logistics_function(X, y, weights):
    z = np.dot(X, weights)
    predictions = 1 / (1 + np.exp(-z))
    loss = -np.mean(y * np.log(predictions) + (1 - y) * np.log(1 - predictions))
    return loss

# 计算逻辑斯蒂克（logistics）目标函数关于参数的梯度
def gradient(X, y, weights):
    z = np.dot(X, weights)
    predictions = 1 / (1 + np.exp(-z))
    error = predictions - y
    grad = np.dot(X.T, error) / len(X)
    return grad

# 小批量梯度下降算法
def mini_batch_gradient_descent(X, y, learning_rate=0.01, batch_size=32, num_epochs=100):
    # 初始化参数
    weights = np.random.randn(X.shape[1]) ##
    
    # 迭代训练
    for epoch in range(num_epochs):
        # 在每个epoch开始时，对训练数据进行洗牌
        shuffled_indices = np.random.permutation(len(X))
        X_shuffled = X[shuffled_indices]
        y_shuffled = y[shuffled_indices]
        
        # 按批次更新参数
        for batch_start in range(0, len(X), batch_size):
            # 获取当前批次的数据
            X_batch = X_shuffled[batch_start:batch_start+batch_size]
            y_batch = y_shuffled[batch_start:batch_start+batch_size]
            losses = []  # 记录损失函数值  --0731add
            gradients = []  # 记录梯度范数 --0731add
            # 计算梯度
            grad = gradient(X_batch, y_batch, weights)       
            # 更新参数
            weights -= learning_rate * grad
            loss_iteration=logistics_function(X, y, weights) #--0731add
            losses.append(loss_iteration)   #--0731add
            gradients.append(np.linalg.norm(grad))  # 计算梯度范数并记录
            
        # 计算当前参数下的目标函数值
        cost = logistics_function(X, y, weights)
        
        # 输出损失
        print("Epoch: {}, Cost: {}".format(epoch, cost))
    return weights
    

# # 创建训练数据（示例数据，自行替换）
# np.random.seed(0)
# X = np.random.randn(1000, 3)
# y = np.random.randint(2, size=1000)

# # 添加偏置项
# X_bias = np.hstack((np.ones((X.shape[0], 1)), X))

# 运行小批量梯度下降算法
mini_batch_gradient_descent(X_bias, y, learning_rate=0.01, batch_size=32, num_epochs=200)


Epoch: 0, Cost: 1.233526075497843
Epoch: 1, Cost: 1.0608433123427659
Epoch: 2, Cost: 0.9541114893203407
Epoch: 3, Cost: 0.897778038022909
Epoch: 4, Cost: 0.866898521332361
Epoch: 5, Cost: 0.8509932657306752
Epoch: 6, Cost: 0.8424559757886418
Epoch: 7, Cost: 0.8373311350558046
Epoch: 8, Cost: 0.834200555933608
Epoch: 9, Cost: 0.8320761922726225
Epoch: 10, Cost: 0.8304482829865532
Epoch: 11, Cost: 0.8290515874783061
Epoch: 12, Cost: 0.8276815580970582
Epoch: 13, Cost: 0.826408775357709
Epoch: 14, Cost: 0.8252077049469461
Epoch: 15, Cost: 0.8240745649422625
Epoch: 16, Cost: 0.822900270936883
Epoch: 17, Cost: 0.8216858004255626
Epoch: 18, Cost: 0.8205352887211343
Epoch: 19, Cost: 0.8194228181827308
Epoch: 20, Cost: 0.8182720142455631
Epoch: 21, Cost: 0.8171649946182411
Epoch: 22, Cost: 0.8160352373956813
Epoch: 23, Cost: 0.8148661615383103
Epoch: 24, Cost: 0.8137493827084618
Epoch: 25, Cost: 0.8126227244659215
Epoch: 26, Cost: 0.8114800659596565
Epoch: 27, Cost: 0.8103904693699239
Epoch: 2

array([ 1.49868142,  0.15022188, -0.44362927,  0.18889514, -0.26953698,
        0.44280433,  0.11662468, -0.4676186 ,  0.16486704,  0.26265873,
        0.66718414, -0.30938882, -0.59388329, -0.05175603, -0.6341884 ,
       -0.25137628, -0.65076391,  0.58552154, -0.31337846, -0.43250244,
       -1.05709188])

In [31]:
import numpy as np

# 定义目标函数
def loss_function(X, y, weights):
    z = np.dot(X, weights)
    predictions = 1 / (1 + np.exp(-z))
    loss = -np.mean(y * np.log(predictions) + (1 - y) * np.log(1 - predictions))
    return loss

# 计算目标函数关于参数的梯度
def gradient(X, y, weights):
    z = np.dot(X, weights)
    predictions = 1 / (1 + np.exp(-z))
    error = predictions - y
    grad = np.dot(X.T, error) / len(X)
    return grad

# KL散度的计算函数
# def kl_divergence(params1, params2):
#     # 根据模型参数计算概率分布
#     # ...

#     # 计算KL散度
#     # kl = ...
#     kl = 0  # 这里需要根据具体的模型参数和KL散度的定义进行计算
#     return kl

def softmax(x):
    exp_x = np.exp(x)
    return exp_x / np.sum(exp_x)
    # 使用Softmax函数将旧模型参数映射到概率分布


def kl_divergence(params1,params2):
 
   # 计算离散概率分布的KL散度
    oldparams_prob = softmax(params1)
    batchparams_prob = softmax(params2)
    kl = np.sum(np.array(oldparams_prob) * np.log(np.array(oldparams_prob)/np.array(batchparams_prob)))
    return kl

# 小批量梯度下降算法
def mini_batch_gradient_descent(X, y, learning_rate=0.01, batch_size=32, num_epochs=100, regularization_weight=0.01):
    # 初始化参数
    weights = np.random.randn(X.shape[1])

    # 保存上一次的参数
    prev_weights = weights.copy()
    
    # 迭代训练
    for epoch in range(num_epochs):
        # 在每个epoch开始时，对训练数据进行洗牌
        shuffled_indices = np.random.permutation(len(X))
        X_shuffled = X[shuffled_indices]
        y_shuffled = y[shuffled_indices]
        
        # 按批次更新参数
        for batch_start in range(0, len(X), batch_size):
            # 获取当前批次的数据
            X_batch = X_shuffled[batch_start:batch_start+batch_size]
            y_batch = y_shuffled[batch_start:batch_start+batch_size]
            
            # 计算梯度
            grad = gradient(X_batch, y_batch, weights)
            
            # 计算KL散度
            kl = kl_divergence(weights, prev_weights)
            
            # 更新参数
            weights -= learning_rate * grad + regularization_weight * kl
            
            # 更新上一次的参数
            prev_weights = weights.copy()
            
        # 计算当前参数下的目标函数值
        cost = loss_function(X, y, weights)
        
        # 输出损失
        print("Epoch: {}, Cost: {}".format(epoch, cost))
    return weights
# 创建训练数据（示例数据，自行替换）
np.random.seed(0)
# X = np.random.randn(1000, 3)
X= np.random.random(size=(1000,20))
y = np.random.randint(2, size=1000)

# 添加偏置项
X_bias = np.hstack((np.ones((X.shape[0], 1)), X))

# 运行小批量梯度下降算法
mini_batch_gradient_descent(X_bias, y, learning_rate=0.01, batch_size=32, num_epochs=200, regularization_weight=0.01)


Epoch: 0, Cost: 1.3096533499586585
Epoch: 1, Cost: 1.12059994255397
Epoch: 2, Cost: 1.0047190193198514
Epoch: 3, Cost: 0.9343446492898251
Epoch: 4, Cost: 0.8944978992568036
Epoch: 5, Cost: 0.8752342277194701
Epoch: 6, Cost: 0.8637996671793882
Epoch: 7, Cost: 0.8570889102138148
Epoch: 8, Cost: 0.8528503196339836
Epoch: 9, Cost: 0.8501181316862969
Epoch: 10, Cost: 0.8480212194753907
Epoch: 11, Cost: 0.845909273243948
Epoch: 12, Cost: 0.844045870902304
Epoch: 13, Cost: 0.8422098397315247
Epoch: 14, Cost: 0.8406860239848936
Epoch: 15, Cost: 0.839052014501159
Epoch: 16, Cost: 0.8374819403658383
Epoch: 17, Cost: 0.835934139332305
Epoch: 18, Cost: 0.834434455478051
Epoch: 19, Cost: 0.8329294455719033
Epoch: 20, Cost: 0.8314228486831742
Epoch: 21, Cost: 0.829838840939376
Epoch: 22, Cost: 0.8283796060526519
Epoch: 23, Cost: 0.82688306416501
Epoch: 24, Cost: 0.8254565468803555
Epoch: 25, Cost: 0.8240115736769243
Epoch: 26, Cost: 0.8226274866059969
Epoch: 27, Cost: 0.8211197815506789
Epoch: 28, C

array([-1.05948316e+00,  2.94291600e-01, -8.79443941e-02,  7.98811782e-01,
        4.96506000e-02,  4.08725033e-01, -5.15544910e-01,  8.65423452e-02,
       -3.92528965e-04,  4.84422262e-01,  1.37085501e-01, -5.61794998e-02,
        4.26863724e-03, -2.88995799e-01, -3.85001106e-01,  1.84249664e-01,
       -2.40840442e-02,  9.15144955e-01,  4.48760020e-01, -2.71688550e-02,
       -1.30481701e-01])

In [23]:
# oldparams_prob=np.random.randn(10)
# batchparams_prob=np.random.randn(10)
oldparams_prob=np.random.random(10)
batchparams_prob=np.random.random(10)
kl = np.sum(np.array(oldparams_prob) * np.log(np.array(oldparams_prob)/np.array(batchparams_prob)))
kl

7.352148476070165

In [24]:
np.random.random(10)

array([0.21815318, 0.59840151, 0.41057459, 0.46041553, 0.66998668,
       0.3596342 , 0.24065582, 0.91822376, 0.34518809, 0.47802094])

In [1]:
import numpy as np

def kl_divergence(p, q):
    """
    计算离散概率分布的KL散度

    参数：
        p: numpy.array，表示概率分布P，要求所有元素都大于0，且和为1
        q: numpy.array，表示概率分布Q，要求所有元素都大于0，且和为1

    返回：
        kl: float，KL散度值
    """
    assert len(p) == len(q), "概率分布的长度不一致"
    assert np.all(p > 0) and np.all(q > 0), "概率分布的所有元素必须大于0"
    assert np.isclose(np.sum(p), 1.0) and np.isclose(np.sum(q), 1.0), "概率分布的和必须为1"

    kl = np.sum(p * np.log(p / q))
    return kl

# 示例：计算两个概率分布的KL散度
p = np.array([0.2, 0.3, 0.5])
q = np.array([0.1, 0.4, 0.5])
kl_value = kl_divergence(p, q)
print("KL散度值为:", kl_value)


KL散度值为: 0.05232481437645474


In [2]:
import numpy as np

def softmax(x):
    exp_x = np.exp(x)
    return exp_x / np.sum(exp_x)

# 旧模型参数向量
old_params = np.array([1.0, 2.0, 3.0, 4.0])

# 使用Softmax函数将旧模型参数映射到概率分布
old_params_prob = softmax(old_params)

print("旧模型参数：", old_params)
print("旧模型参数概率分布：", old_params_prob)
print("概率分布的和：", np.sum(old_params_prob))


旧模型参数： [1. 2. 3. 4.]
旧模型参数概率分布： [0.0320586  0.08714432 0.23688282 0.64391426]
概率分布的和： 1.0


In [26]:
import numpy as np

# 定义逻辑斯蒂克（logistics）目标函数
def logistics_function(X, y, weights):
    z = np.dot(X, weights)
    predictions = 1 / (1 + np.exp(-z))
    loss = -np.mean(y * np.log(predictions) + (1 - y) * np.log(1 - predictions))
    return loss

# 计算逻辑斯蒂克（logistics）目标函数关于参数的梯度
def gradient(X, y, weights):
    z = np.dot(X, weights)
    predictions = 1 / (1 + np.exp(-z))
    error = predictions - y
    grad = np.dot(X.T, error) / len(X)
    return grad

# 小批量梯度下降算法
def mini_batch_gradient_descent(X, y, learning_rate=0.01, batch_size=32, num_epochs=100):
    # 初始化参数
    weights = np.random.randn(X.shape[1])
    
    # 迭代训练
    for epoch in range(num_epochs):
        # 在每个epoch开始时，对训练数据进行洗牌
        shuffled_indices = np.random.permutation(len(X))
        X_shuffled = X[shuffled_indices]
        y_shuffled = y[shuffled_indices]
        
        # 按批次更新参数
        for batch_start in range(0, len(X), batch_size):
            # 获取当前批次的数据
            X_batch = X_shuffled[batch_start:batch_start+batch_size]
            y_batch = y_shuffled[batch_start:batch_start+batch_size]
            
            # 计算梯度
            grad = gradient(X_batch, y_batch, weights)
            
            # 更新参数
            weights -= learning_rate * grad
            
        # 计算当前参数下的目标函数值
        cost = logistics_function(X, y, weights)
        
        # 输出损失
        print("Epoch: {}, Cost: {}".format(epoch, cost))
    return weights
    

# # 创建训练数据（示例数据，自行替换）
# np.random.seed(0)
# X = np.random.randn(1000, 3)
# y = np.random.randint(2, size=1000)

# # 添加偏置项
# X_bias = np.hstack((np.ones((X.shape[0], 1)), X))

# 运行小批量梯度下降算法
mini_batch_gradient_descent(X_bias, y, learning_rate=0.01, batch_size=32, num_epochs=200)


Epoch: 0, Cost: 1.1149677056433556
Epoch: 1, Cost: 1.087996620117277
Epoch: 2, Cost: 1.0618960821422725
Epoch: 3, Cost: 1.0358900921524437
Epoch: 4, Cost: 1.0114994150846943
Epoch: 5, Cost: 0.9880123484141561
Epoch: 6, Cost: 0.9656273186595019
Epoch: 7, Cost: 0.9438761708862489
Epoch: 8, Cost: 0.9234876831400546
Epoch: 9, Cost: 0.9042946658740616
Epoch: 10, Cost: 0.8858925180478097
Epoch: 11, Cost: 0.8683655856812188
Epoch: 12, Cost: 0.8519484795570893
Epoch: 13, Cost: 0.8371306215860157
Epoch: 14, Cost: 0.8227714090892063
Epoch: 15, Cost: 0.8090556278775695
Epoch: 16, Cost: 0.7970894191154226
Epoch: 17, Cost: 0.7860604913596378
Epoch: 18, Cost: 0.7760371688721439
Epoch: 19, Cost: 0.7668103637428171
Epoch: 20, Cost: 0.7585038392224709
Epoch: 21, Cost: 0.7509655207238668
Epoch: 22, Cost: 0.7441039105333611
Epoch: 23, Cost: 0.7375396328954794
Epoch: 24, Cost: 0.7320652887315464
Epoch: 25, Cost: 0.7268913012033891
Epoch: 26, Cost: 0.7225576881214972
Epoch: 27, Cost: 0.7185723006641379
Epo

array([ 0.14333691, -0.05989198,  0.07544325, -0.06099479])

In [49]:
standard_weight = np.random.randn(X.shape[1])
standard_weight.shape

(40,)

In [48]:
X.shape[1]

40

In [58]:
import numpy as np

# 定义目标函数
def loss_function(X, y, weights):
    z = np.dot(X, weights)
    predictions = 1 / (1 + np.exp(-z))
    loss = -np.mean(y * np.log(predictions) + (1 - y) * np.log(1 - predictions))
    return loss

# 计算目标函数关于参数的梯度
def gradient(X, y, weights):
    z = np.dot(X, weights)
    predictions = 1 / (1 + np.exp(-z))
    error = predictions - y
    grad = np.dot(X.T, error) / len(X)
    return grad

# KL散度的计算函数
# def kl_divergence(params1, params2):
#     # 根据模型参数计算概率分布
#     # ...

#     # 计算KL散度
#     # kl = ...
#     kl = 0  # 这里需要根据具体的模型参数和KL散度的定义进行计算
#     return kl

def softmax(x):
    exp_x = np.exp(x)
    return exp_x / np.sum(exp_x)
    # 使用Softmax函数将旧模型参数映射到概率分布


def kl_divergence(params1,params2):
 
   # 计算离散概率分布的KL散度
    oldparams_prob = softmax(params1)
    batchparams_prob = softmax(params2)
    kl = np.sum(np.array(oldparams_prob) * np.log(np.array(oldparams_prob)/np.array(batchparams_prob)))
    return kl

# 小批量梯度下降算法
def mini_batch_gradient_descent(X, y, learning_rate=0.001, batch_size=32, num_epochs=100, regularization_weight=0.1):
    # 初始化参数
    # weights = np.random.randn(X.shape[1])
    weights= standard_weight
    # 保存上一次的参数
    prev_weights = weights.copy()
    
    # 迭代训练
    for epoch in range(num_epochs):
        # 在每个epoch开始时，对训练数据进行洗牌
        shuffled_indices = np.random.permutation(len(X))
        X_shuffled = X[shuffled_indices]
        y_shuffled = y[shuffled_indices]
        
        # 按批次更新参数
        for batch_start in range(0, len(X), batch_size):
            # 获取当前批次的数据
            X_batch = X_shuffled[batch_start:batch_start+batch_size]
            y_batch = y_shuffled[batch_start:batch_start+batch_size]
            
            # 计算梯度
            grad = gradient(X_batch, y_batch, weights)
            
            # 计算KL散度
            kl = kl_divergence(weights, prev_weights)
            
            # 更新参数
            weights -= learning_rate * grad + regularization_weight * kl
            
            # 更新上一次的参数
            prev_weights = weights.copy()
            
        # 计算当前参数下的目标函数值
        cost = loss_function(X, y, weights)
        
        # 输出损失
        print("Epoch: {}, Cost: {}".format(epoch, cost))
    return weights
# 创建训练数据（示例数据，自行替换）
np.random.seed(0)
# X = np.random.randn(1000, 3)
X= np.random.random(size=(1000,39))
y = np.random.randint(2, size=1000)

# 添加偏置项
X_bias = np.hstack((np.ones((X.shape[0], 1)), X))

# 运行小批量梯度下降算法
mini_batch_gradient_descent(X_bias, y, learning_rate=0.01, batch_size=32, num_epochs=300, regularization_weight=0.01)


Epoch: 0, Cost: 0.6715693770962268
Epoch: 1, Cost: 0.6715660106953437
Epoch: 2, Cost: 0.6715912990636204
Epoch: 3, Cost: 0.6715958640482066
Epoch: 4, Cost: 0.6715950677887222
Epoch: 5, Cost: 0.6716051336070907
Epoch: 6, Cost: 0.6715816078764367
Epoch: 7, Cost: 0.671566334133661
Epoch: 8, Cost: 0.671567096587632
Epoch: 9, Cost: 0.6717385670894361
Epoch: 10, Cost: 0.6716708299014352
Epoch: 11, Cost: 0.6715668621545555
Epoch: 12, Cost: 0.6719116232507073
Epoch: 13, Cost: 0.671751404719541
Epoch: 14, Cost: 0.671893059540073
Epoch: 15, Cost: 0.6715934674857714
Epoch: 16, Cost: 0.6715709644203864
Epoch: 17, Cost: 0.6715701458717462
Epoch: 18, Cost: 0.6717006861033463
Epoch: 19, Cost: 0.6716255261635351
Epoch: 20, Cost: 0.6717055663359665
Epoch: 21, Cost: 0.6715772303393327
Epoch: 22, Cost: 0.6715796022988956
Epoch: 23, Cost: 0.6715648899783462
Epoch: 24, Cost: 0.6716005365734551
Epoch: 25, Cost: 0.6716265887727659
Epoch: 26, Cost: 0.671564049648994
Epoch: 27, Cost: 0.6717349726739863
Epoch: 

array([ 0.55097321, -0.01073398, -0.06475282,  0.11195287, -0.17989966,
       -0.33710224, -0.12955031, -0.53813607, -0.44203356,  0.08015904,
        0.3003148 , -0.27260057,  0.37144702, -0.04545986, -0.22080118,
       -0.35641876,  0.15124222,  0.05201362,  0.04645895, -0.26709189,
        0.22615389, -0.23540706,  0.05210057, -0.13346274,  0.19189372,
       -0.15522687, -0.20296934, -0.09332131,  0.42972255,  0.13704143,
        0.1398835 ,  0.14624136,  0.16335998,  0.05637193,  0.15886293,
        0.1094274 ,  0.23154241,  0.03389491, -0.59832433, -0.11905291])

In [57]:
import numpy as np

# 定义逻辑斯蒂克（logistics）目标函数
def logistics_function(X, y, weights):
    z = np.dot(X, weights)
    predictions = 1 / (1 + np.exp(-z))
    loss = -np.mean(y * np.log(predictions) + (1 - y) * np.log(1 - predictions))
    return loss

# 计算逻辑斯蒂克（logistics）目标函数关于参数的梯度
def gradient(X, y, weights):
    z = np.dot(X, weights)
    predictions = 1 / (1 + np.exp(-z))
    error = predictions - y
    grad = np.dot(X.T, error) / len(X)
    return grad

# 小批量梯度下降算法
def mini_batch_gradient_descent(X, y, learning_rate=0.01, batch_size=32, num_epochs=100):
    # 初始化参数
    # weights = np.random.randn(X.shape[1])
    weights = standard_weight
    
    # 迭代训练
    for epoch in range(num_epochs):
        # 在每个epoch开始时，对训练数据进行洗牌
        shuffled_indices = np.random.permutation(len(X))
        X_shuffled = X[shuffled_indices]
        y_shuffled = y[shuffled_indices]
        
        # 按批次更新参数
        for batch_start in range(0, len(X), batch_size):
            # 获取当前批次的数据
            X_batch = X_shuffled[batch_start:batch_start+batch_size]
            y_batch = y_shuffled[batch_start:batch_start+batch_size]
            
            # 计算梯度
            grad = gradient(X_batch, y_batch, weights)
            
            # 更新参数
            weights -= learning_rate * grad
            
        # 计算当前参数下的目标函数值
        cost = logistics_function(X, y, weights)
        
        # 输出损失
        print("Epoch: {}, Cost: {}".format(epoch, cost))
    return weights
    

# # 创建训练数据（示例数据，自行替换）
# np.random.seed(0)
# X = np.random.randn(1000, 3)
# y = np.random.randint(2, size=1000)

# # 添加偏置项
# X_bias = np.hstack((np.ones((X.shape[0], 1)), X))

# 运行小批量梯度下降算法
mini_batch_gradient_descent(X_bias, y, learning_rate=0.01, batch_size=32, num_epochs=300)


Epoch: 0, Cost: 0.6716188921350539
Epoch: 1, Cost: 0.6716281895996586
Epoch: 2, Cost: 0.6715966152601636
Epoch: 3, Cost: 0.6715969385656927
Epoch: 4, Cost: 0.6715962115402176
Epoch: 5, Cost: 0.6715966806045798
Epoch: 6, Cost: 0.6716440598134604
Epoch: 7, Cost: 0.6716607159330591
Epoch: 8, Cost: 0.6717224625710937
Epoch: 9, Cost: 0.6717471803665953
Epoch: 10, Cost: 0.6718583751546048
Epoch: 11, Cost: 0.6716525243080544
Epoch: 12, Cost: 0.6715971191552836
Epoch: 13, Cost: 0.6717713725795598
Epoch: 14, Cost: 0.671724635783806
Epoch: 15, Cost: 0.6716139894608296
Epoch: 16, Cost: 0.6716498030448759
Epoch: 17, Cost: 0.6716001481246814
Epoch: 18, Cost: 0.6715951951420216
Epoch: 19, Cost: 0.6716690308074224
Epoch: 20, Cost: 0.6716043027432357
Epoch: 21, Cost: 0.6715963358534816
Epoch: 22, Cost: 0.6717204094905465
Epoch: 23, Cost: 0.6716508458170144
Epoch: 24, Cost: 0.6718455751682368
Epoch: 25, Cost: 0.6717917071796096
Epoch: 26, Cost: 0.6716055815552215
Epoch: 27, Cost: 0.6716321807399638
Epo

array([ 0.59109889, -0.01578179, -0.0725431 ,  0.1062567 , -0.18950367,
       -0.3376476 , -0.13491071, -0.54030759, -0.45237247,  0.0815235 ,
        0.29541645, -0.27135088,  0.36880911, -0.04822   , -0.22322151,
       -0.34611111,  0.15298622,  0.04611128,  0.04918297, -0.26603479,
        0.21901128, -0.23313296,  0.04323745, -0.13930529,  0.19338318,
       -0.15718686, -0.20866278, -0.09861212,  0.4208175 ,  0.13223673,
        0.13862056,  0.15026483,  0.16059871,  0.06046491,  0.14983613,
        0.10738614,  0.23299906,  0.0291932 , -0.59955402, -0.12084722])